from stats import Stats

NUM_SIMULATIONS: int = 1000
NUM_SELECTABLE_STATS: int = 6
NUM_FEMALES: int = 800

MALE_SUB_20_MUTATIONS: bool = False
FEMALES_SUB_20_MUTATIONS: bool = False

DESIRED_STAT = Stats.HEALTH